Additional Workshed Support
tigerinanenet/cognac pull request #27
Opened 2023-07-26 13:11 UTC by Xyghra

should allow support for CMC + Trainset in addition to asdon. Right now it simply prioritizes asdon > cmc > trainset but I have no calculations to support this choice, It has very little testing since swapping worksheds is a once/day deal and I don't own an asdon

2023-07-28 17:25 UTC, tigerinanenet requested changes

2023-07-28 17:25 UTC, tigerinanenet commented on src/quests/prologue/tasks/asdon.ts
> +    (CMCInstalled() && get(`_coldMedicineConsults`) < 5),
Let's keep CMC out of this file.

Can do something like
```
ready: () => get(ASDON)
```

2023-07-28 17:25 UTC, tigerinanenet commented on src/quests/prologue/tasks/cmc.ts
> +  if (!get(CMC)) {
This is misleading logic in a function named `CMCInstalled`

2023-07-28 17:25 UTC, tigerinanenet commented on src/quests/prologue/tasks/cmc.ts
> +export function CMCInstalled(): boolean {
This function doesn't seem to be checking if the CMC is actually installed. Please reconsider the function name, or move around the function logic to better reflect this method signature.

2023-07-28 17:25 UTC, tigerinanenet commented on src/quests/prologue/tasks/cmc.ts
> +  completed: () => get(`_workshedItemUsed`) || myAdventures() > 81 || CMCInstalled(),
Can we move the `myAdventures` logic to a `ready` clause?

2023-07-28 17:25 UTC, tigerinanenet commented on src/quests/prologue/tasks/cmc.ts
> +    !CMCPillReady(),
Let's move this to the ready clause.

2023-07-28 17:25 UTC, tigerinanenet commented on src/quests/prologue/tasks/train.ts
> +    (CMCInstalled() && get(`_coldMedicineConsults`) < 5),
Let's keep CMC out of this method. With 3 worksheds supported, I think it makes sense to refactor the `useAsdon` property to a `worshed` property, accepting `train,cmc,asdon`.

2023-07-28 17:25 UTC, tigerinanenet commented on src/quests/prologue/tasks/train.ts
> +    ].includes(TrainSet.next()),
I'm not sure I understand why this is the ready condition.

2023-07-30 00:31 UTC, Xyghra commented
I think this resolves most of the requested changes. The first one, I'm just genuinely clueless on how to check and make sure I'm not overwriting CMC early without including any CMC related functions in the file. I did the best I could with what I know how to do in the end, apologies if it's not to your liking.

2023-07-30 20:00 UTC, tigerinanenet requested changes

2023-07-30 20:00 UTC, tigerinanenet commented on src/quests/prologue/tasks/asdon.ts
> +  if (desiredWorksheds.includes(`asdon`)) {
Nested if statements are really tricky to understand. We can use the guard pattern here. When cleaned up, the code may look something like this:
```
if (!desiredWorksheds.includes(`asdon`)) {
    return false;
}
if (have($item`Asdon Martin keyfob`)) {
    return false
}
return CMCInProgress();

2023-07-30 20:00 UTC, tigerinanenet commented on src/quests/prologue/tasks/asdon.ts
> +  do: () => use($item`Asdon Martin keyfob`),
nice cleanup! :+1:

2023-07-30 20:00 UTC, tigerinanenet commented on src/quests/prologue/tasks/cmc.ts
> +  if (get(WORKSHED).split(`,`).includes(`cmc`)) {
We can use the guard pattern here as well.

2023-07-30 20:00 UTC, tigerinanenet commented on src/quests/prologue/tasks/cmc.ts
> +function CMCInstalled(): boolean {
It's a little weird, but the convention is to have even abbreviations be lowercase if they start a signature/method name
```
cmcInstalled
```
would be the preferred name.

2023-07-30 20:00 UTC, tigerinanenet commented on src/quests/prologue/tasks/cmc.ts
> +};
nice!

2023-07-30 20:00 UTC, tigerinanenet commented on src/quests/prologue/tasks/train.ts
> +function shouldInstallTrain(): boolean {
Lets use the guard pattern here too.

2023-07-30 23:46 UTC, Xyghra commented
👍

2024-07-05 01:43 UTC, closed without merging